<?php
$n=5;
$n_1=2;
$n_2=5;
$d_1="W";
$d_2="S";
$pi=pi();
for($i=1;$i<=2;$i++){
  if($i==1){
    $s["n"]=${"n_".$i};
    $s["c"]=${"d_".$i};
  }else{
    $g["n"]=${"n_".$i};
    $g["c"]=${"d_".$i};
  }
}
$d[]=$s["c"];
$d[]=$g["c"];
usort($d,"strnatcmp");
$j=$d[0].$d[1];
if($j=="NN"||$j=="EE"||$j=="SS"||$j=="WW"){
  $a=abs($s["n"]-$g["n"]);
}elseif($j=="EW"||$j=="NS"){
  $a=$s["n"]+$g["n"];
}else{
  if($s["n"]==$g["n"]){
    $a=$g["n"]*$pi/2;
  }elseif($s["n"]>$g["n"]){
    $a=$g["n"]*$pi/2+$s["n"]-$g["n"];
  }else{
    $a=$s["n"]*$pi/2+$g["n"]-$s["n"];
  }
}
echo $a*100;
?>